### ISSUE TITLE
Code was not working until I added "NewRemoteHost"

### ISSUE THREAD

**Issue by JL1946** [gryphius/port-forward#1]
Hello:

I used your code to implement upnp port forwarding for a Linksys Router.
The router was continually sending back Error 402 and failing to accept the command until I modified the code to include "NewRemoteHost" in the stream sent to the router.
I set "NewRemoteHost" = to "" .
The updated code looks like this:

   arguments = [
        ('NewRemoteHost', ""),                                        # unused - but required
        ('NewExternalPort', external_port),                     # specify port on router
        ('NewProtocol', protocol),                                    # specify protocol
        ('NewInternalPort', internal_port),                       # specify port on internal host
        ('NewInternalClient', internal_client),                   # specify IP of internal host
        ('NewEnabled', enabled),                                      # turn mapping ON
        ('NewPortMappingDescription', description),     # add a description
        ('NewLeaseDuration', duration)]                          # how long should it be opened?

**Comment by gryphius** [comment]
Cool, thanks! Do you want to make a pull request? If not i can just add the line, but a PR gives you proper credit automatically

**Comment by JL1946** [comment]
Not necessary - please add the line. Thanks
Works very well BTW...
